### PR TITLE
Fix for #69

### LINKED ISSUE #69: div.panel-body-contents too high on many Firefoxes
bildschirmfoto 2015-09-25 um 07 25 42
Repro with several current Firefox versions. If you scroll down some, the \<h4> and UI Elements for Chat switching appear...

### PR DESCRIPTION
**Pull request by JSey**
Works in our production instance and has no apparent side effects. Fixes #69.

### CODE REVIEW

**Comment by gdpelican** [comment]
Hm, not sure I quite understand this fix, @JSey?

Here's a gif of me applying that style on Firefox 40:
http://g.recordit.co/Bj6A3ESvzU.gif

And on chrome latest:
http://g.recordit.co/bXCVlFuJ2L.gif

**Comment by JSey** [comment]
Wait a minute - why is .babble-title-wrapper styled `position: fixed`? That does the trick for me, too - ah. I see. It's the old problem “browser window size”. in `.drop-down .babble-title-wrapper`, the style is defined as `position: absolute`. Which breaks positioning by approx. 1000px. I guess I should modify the PR, since I have the same behavior with a smaller browser window…

**Comment by gdpelican** [comment]
I think what we have here is a delightful case of
css_is_awesome

**Comment by JSey** [comment]
:laughing:

**Comment by JSey** [comment]
Here it comes again. Would you rather have a PR with a single commit? I did not want to throw this one completely into the bin… ^^

**Comment by gdpelican** [comment]
Nah, I'm not fussed. I'll spin it up and try it out in a bit, thanks again!

**Comment by gdpelican** [comment]
Hrm, this is breaking my latest chrome
screen shot 2015-11-22 at 5 33 55 am

and Firefox 40:
screen shot 2015-11-22 at 5 34 57 am

Not quite sure what the disparity is between our setups, but I'm afraid the answer might just be that the sidebar isn't set up very well to contain a scrollable div, and the hack(s) I came up with to workaround that isn't Xbrowser enough.

I'll take some time in the next while to investigate further and see if we can't come up with a more confident css approach to this thing.

**Comment by JSey** [comment]
Let me re-check this. I experience the original problem with the title and channel switcher with Firefox on discourse-babble.com, too (sry for the file size):
babble

…note the title bar when I resize toe browser window so that it un-docks.

**Comment by JSey** [comment]
Are you sure you added the styles correctly for testing? I did this with a (addmittedly relatively) vanilla Discourse install:

babble-p5

…and all my browsers display discourse-babble.com correctly if I modify the styles like so:

https://github.com/JSey/babble/blob/patch-5/assets/stylesheets/babble.scss#L180

(most important thing is to make .drop-down .babble-title-wrapper fixed while the composer needs to be absolute - the first try with the top: spec did not work. See https://github.com/JSey/babble/blob/patch-5/assets/stylesheets/babble.scss#L180 for the whole file).

**Comment by gdpelican** [comment]
Hm, not sure what the difference was between applying styling manually and putting them in the stylesheet, but this seems to work alright once I actually pull down the branch and give it a go.

In any case, thanks @JSey, I'm going to merge this in; let me know if there's additional browser stuff that's broken; looks ok from my end.

**Pull request merged**
