### PR TITLE
Don't show unread count when dropdown is visible or babble icon is not visible

### PR DESCRIPTION
**Pull request by gtanczyk**
Fix for #4, the idea is to just not show unread count, when dropdown is visible.

### CODE REVIEW

**Comment by JSey** [comment]
Great idea.

**Comment by gdpelican** [comment]
Thanks for this, @gtanczyk!

Hm, this strikes me as a band-aid on the real issue, which is that the #read action on BabbleController should mark the newly created post as read on the TopicUser. Then, when the new post comes through, it should update the topic immediately.

Also, I _want_ the notification to show up if you're, say, scrolled back a day or two of messages, and someone sends a new message.

**Comment by gtanczyk** [comment]
Do you mean to do that here?

    class ::Babble::TopicsController < ::ApplicationController
    // ...
      def post
        Babble::PostCreator.create(current_user, post_creator_params)
        // mark as read
        head :ok
      end

**Comment by gdpelican** [comment]
I think so, yes. The other option would be to look into the PostCreator
(which Babble::PostCreator in inheriting from) to see where / if the post
gets marked read there in regular Discourse, or if we have to do it
ourselves in the controller action.

**Comment by gtanczyk** [comment]
Tried to put this here, but does not work:

    class ::Babble::PostCreator < ::PostCreator

      # ...

      def trigger_after_events(post)
        super
      
        TopicUser.update_last_read(@user, @topic.id, @post.post_number, PostTiming::MAX_READ_TIME_PER_BATCH)

        MessageBus.publish "/babble/topic", serialized_topic
        MessageBus.publish "/babble/post", serialized_post.merge!(type: :created)
      end

Any ideas?

**Comment by gdpelican** [comment]
Hm, none off the top of my head, but hoping to have the chance to spin this up over the weekend a little, so can give more better thoughts then.

**Comment by gdpelican** [comment]
Hm, I think the issue may be that we're not passing a `@user` to the TopicView in `serialized_topic` in the PostCreator, so it doesn't pass the read information along.

```
    def serialized_topic
      TopicViewSerializer.new TopicView.new(@topic.id, @user), # etc...
    end
```
might do the trick.

**Comment by gdpelican** [comment]
Actually, scratch that, that's no good, since it'll serialize out the read data for the current user to all clients.

**Comment by gdpelican** [comment]
Think I may have fixed this one inadvertently in #16; key was to return the topic view via the read action. Thanks again for putting your head into this!

**Comment by gtanczyk** [comment]
No worries :)

**Pull request closed without merging**
